---
title: "SimAnnealComplete"
author: "Paul M"
date: "1/21/2021"
output: html_document
---


A couple of test functions:
```{r}
XYSquared <- function(x)
{
	return ((x[1]^2+x[2]^2))
}

source('Rosenbrock.r')
MyRosenbrock<-function(x){
  return (Rosenbrock(x)[[1]])
}
```

And now the SA algorithm
```{r}
SimAnneal2D <- function(Fn,StartPoint,InitialTemp,FinalTemp,TempDecreaseRate){
	StepSize <- 2
	Count  <-  0
	X <- StartPoint[1]
	Y <- StartPoint[2]
	#FnVal <-  Fn(X,Y)
	FnVal <-  Fn(StartPoint)
	Temp <- InitialTemp
	plot(X,Y,xlim=c(-2*X,2*X),ylim=c(-2*Y,2*Y))
	points(0,0,pch=19,col="red")
	while (Temp>FinalTemp){
		#propose new point
		NewX <- X+rnorm(1,mean=0,sd=StepSize)
		NewY <- Y+rnorm(1,mean=0,sd=StepSize)

		#decide whether to move
		New <- c(NewX,NewY)
		NewVal <- Fn(New)
		h <- min(1,exp(-1*(NewVal-FnVal)/Temp))
		p <- runif(1)
		if (p<h){ #move
		  arrows(X,Y,NewX,NewY,length=0.05)
		  X <- New[1]
			Y <- New[2]
			# pause for a bit so that it moves at a speed that you can see
			Start.Time <- Sys.time()
			while (Sys.time()<Start.Time+0.2){}
			# plot the path you are taking
			points(X,Y,pch='.',col="blue")
			FnVal <- NewVal
			}

		#cat(paste(Count,NewVal,OldX,OldY,X,Y,"\n"))
		#reduce temperature
		Temp <- Temp*(1-TempDecreaseRate)
		Count <- Count+1
	}
	return (c(X,Y,FnVal))  # return the estimated location of the minimum
}
```

And now to test it
```{r}
set.seed(34)
Result <- SimAnneal2D(XYSquared,c(20,10),10,0.1,0.02)
cat("\nWe ended up at:",Result[1],Result[2]," with a value of ",Result[3])
Start <- c(5.1,3.1)
Result <- SimAnneal2D(MyRosenbrock,Start,10,0.1,0.002)
cat("\nWe ended up at:",Result[1],Result[2]," with a value of ",Result[3])
```

